site_name: Ekaterina Kormilitsyna

theme:
  name: material
  theme:
    palette:
      scheme: slate
      primary: black


markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

