site_name: Ekaterina Kormilitsyna

theme:
  name: material
  palette:
    primary: black
    scheme: slate
    accent: light green
  font:
    text: Roboto Mono
    code: Roboto Mono


markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

